/**
 * withXCollabNetwork — Expo config plugin that installs XCollab's network
 * policy into every HTTP stack React Native uses (fetch/XHR and WebSocket).
 *
 * Derived from the field-proven XCompass/XMaps plugin (withClientMtls.js),
 * minus the mTLS parts XCollab does not need: service8.nexedge.ae presents a
 * PUBLIC Sectigo wildcard certificate (*.nexedge.ae), so server TLS validates
 * against the stock system trust store — no custom CA, no MDM, no cleartext.
 *
 * What the policy does and why:
 *
 *  1. Pinned-host DNS. Public DNS does not resolve service8.nexedge.ae to the
 *     intranet edge yet (network-team request pending), and phones cannot
 *     carry a hosts-file line the way demo laptops do. The plugin reads
 *     `expo.extra.pinnedHosts` from app.json and resolves those hostnames to
 *     the given IPs inside OkHttp. TLS still handshakes with the real
 *     hostname (SNI + hostname verification against the wildcard cert), so
 *     this is exactly the laptop hosts-line, scoped to the app. When the
 *     public edge starts forwarding service8, delete the entry and rebuild.
 *
 *  2. HTTP/1.1 only. The nexedge.ae services share one edge IP and one
 *     wildcard cert, so OkHttp coalesces HTTP/2 connections across hosts.
 *     The Istio edge routes by TLS SNI: a request riding a connection opened
 *     for a different host lands in the wrong filter chain and 404s. XMaps
 *     hit this in the field; HTTP/1.1 connections are never coalesced.
 *
 *  3. IPv4-first DNS ordering for non-pinned hosts. Device Wi-Fi networks
 *     observed in the field advertise AAAA records with a black-holed IPv6
 *     path; OkHttp tries addresses in resolver order and stalls past the
 *     JS request budget. Sorting A records first makes requests
 *     deterministic; hosts without A records are unaffected.
 *
 * iOS is not wired yet — this plugin is Android-first (the iOS NSURLSession
 * equivalent lands with the iOS build).
 */
const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const kotlinSource = (pkg, pinnedHosts) => {
  const entries = Object.entries(pinnedHosts)
    .map(([host, ip]) => `        "${host}" to "${ip}",`)
    .join('\n');
  return `package ${pkg}

import android.content.Context
import android.util.Log
import com.facebook.react.modules.network.OkHttpClientProvider
import com.facebook.react.modules.websocket.WebSocketModule
import java.net.Inet4Address
import java.net.InetAddress
import okhttp3.Dns
import okhttp3.OkHttpClient
import okhttp3.Protocol

/**
 * Generated by plugins/withXCollabNetwork.js — edits inside android/ are lost
 * on the next prebuild. Pinned hosts come from expo.extra.pinnedHosts.
 */
private class XCollabDns : Dns {
    override fun lookup(hostname: String): List<InetAddress> {
        val pin = PINNED[hostname]
        // Loopback first: with a USB tunnel active (adb reverse tcp:443 →
        // host proxy → intranet edge) it connects instantly; without one the
        // local connect is refused immediately and OkHttp falls through to
        // the pinned intranet IP (reachable on corp-VPN networks). TLS still
        // verifies against the real hostname either way.
        if (pin != null) {
            return listOf(InetAddress.getByName("127.0.0.1"), InetAddress.getByName(pin))
        }
        return Dns.SYSTEM.lookup(hostname).sortedBy { if (it is Inet4Address) 0 else 1 }
    }

    private companion object {
        val PINNED: Map<String, String> = mapOf(
${entries}
        )
    }
}

object XCollabNetwork {
    private const val TAG = "XCollabNetwork"

    private fun applyPolicy(builder: OkHttpClient.Builder): OkHttpClient.Builder =
        builder
            .dns(XCollabDns())
            .protocols(listOf(Protocol.HTTP_1_1))
            // Two candidate addresses per pinned host — keep the per-address
            // connect attempt short so falling through stays snappy.
            .connectTimeout(6, java.util.concurrent.TimeUnit.SECONDS)

    fun install(context: Context) {
        OkHttpClientProvider.setOkHttpClientFactory {
            applyPolicy(OkHttpClientProvider.createClientBuilder(context)).build()
        }
        WebSocketModule.setCustomClientBuilder { builder -> applyPolicy(builder) }
        Log.i(TAG, "Network policy installed: pinned-host DNS, IPv4-first, HTTP/1.1")
    }
}
`;
};

function withXCollabNetwork(config) {
  const pkg = config.android?.package;
  if (!pkg) throw new Error('[withXCollabNetwork] android.package missing from app config');
  const pinnedHosts = config.extra?.pinnedHosts ?? {};

  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const srcDir = path.join(root, 'app/src/main/java', ...pkg.split('.'));
      fs.mkdirSync(srcDir, { recursive: true });
      fs.writeFileSync(path.join(srcDir, 'XCollabNetwork.kt'), kotlinSource(pkg, pinnedHosts));
      return cfg;
    },
  ]);

  config = withMainApplication(config, (cfg) => {
    if (!cfg.modResults.contents.includes('XCollabNetwork.install')) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /super\.onCreate\(\)/,
        'super.onCreate()\n    XCollabNetwork.install(this)'
      );
    }
    return cfg;
  });

  return config;
}

module.exports = withXCollabNetwork;
