export type UiLanguage = "en" | "ar";

interface Dictionary {
  brand: string;
  tagline: string;
  missionLabel: string;
  missionPlaceholder: string;
  timelineStart: string;
  timelineEnd: string;
  generate: string;
  generating: string;
  programsHeading: string;
  emptyState: string;
  ledgerVerified: string;
  ledgerInvalid: string;
  ledgerHeading: string;
  packagesHeading: string;
  tasksLabel: string;
  milestonesHeading: string;
  risksHeading: string;
  teamsHeading: string;
  generatedBy: string;
  errorGeneric: string;
  languageToggle: string;
  themeLight: string;
  themeDark: string;
  themeSystem: string;
  navOverview: string;
  navPrograms: string;
  navLedger: string;
  navTeams: string;
  navSoon: string;
  workspace: string;
  statPrograms: string;
  statPackages: string;
  statTasks: string;
  statChain: string;
  statusTodo: string;
  statusInProgress: string;
  statusBlocked: string;
  statusDone: string;
  actorHuman: string;
  actorAi: string;
  actorService: string;
  severityLow: string;
  severityMedium: string;
  severityHigh: string;
  severityCritical: string;
  colSeq: string;
  colActor: string;
  colAction: string;
  colModel: string;
  colTime: string;
  colHash: string;
  colPrevHash: string;
  chainIntact: string;
  chainBrokenAt: string;
  backToPrograms: string;
  notFound: string;
  openProgram: string;
  estimateDaysSuffix: string;
  ledgerEmpty: string;
  viewSwitcherLabel: string;
  viewList: string;
  viewBoard: string;
  boardColumnEmpty: string;
  taskMoveFailed: string;
  taskName: string;
  taskStatus: string;
  taskStartDate: string;
  taskDueDate: string;
  taskEstimate: string;
  taskAssigneeRole: string;
  taskDescription: string;
  taskActivity: string;
  addTask: string;
  deleteTask: string;
  confirmDelete: string;
  taskCreated: string;
  taskDeleted: string;
  taskUpdated: string;
  undo: string;
  close: string;
  lastTaskInPackage: string;
}

export const STRINGS: Record<UiLanguage, Dictionary> = {
  en: {
    brand: "XCollab",
    tagline: "Describe the mission. The program builds itself.",
    missionLabel: "Mission brief",
    missionPlaceholder:
      "e.g. Stand up a sovereign field-logistics program across three regional hubs by Q4",
    timelineStart: "Start",
    timelineEnd: "Target end",
    generate: "Generate program",
    generating: "Generating…",
    programsHeading: "Programs",
    emptyState: "No programs yet. State a mission above to generate the first one.",
    ledgerVerified: "Ledger verified",
    ledgerInvalid: "Ledger verification failed",
    ledgerHeading: "AI action ledger",
    packagesHeading: "Work packages",
    tasksLabel: "tasks",
    milestonesHeading: "Milestones",
    risksHeading: "Risks",
    teamsHeading: "Teams",
    generatedBy: "Generated by",
    errorGeneric: "Generation failed. Check that the API is running and try again.",
    languageToggle: "العربية",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "Auto",
    navOverview: "Overview",
    navPrograms: "Programs",
    navLedger: "AI Ledger",
    navTeams: "Teams",
    navSoon: "Soon",
    workspace: "HQ Workspace",
    statPrograms: "Programs",
    statPackages: "Work packages",
    statTasks: "Tasks",
    statChain: "Chain integrity",
    statusTodo: "To do",
    statusInProgress: "In progress",
    statusBlocked: "Blocked",
    statusDone: "Done",
    actorHuman: "Human",
    actorAi: "AI",
    actorService: "Service",
    severityLow: "Low",
    severityMedium: "Medium",
    severityHigh: "High",
    severityCritical: "Critical",
    colSeq: "Seq",
    colActor: "Actor",
    colAction: "Action",
    colModel: "Model",
    colTime: "Occurred at",
    colHash: "Hash",
    colPrevHash: "Previous hash",
    chainIntact: "Every entry verifies against its content hash and links to its predecessor.",
    chainBrokenAt: "Chain verification failed",
    backToPrograms: "Back to programs",
    notFound: "Program not found.",
    openProgram: "Open",
    estimateDaysSuffix: "days",
    ledgerEmpty: "No ledger entries yet. Generate a program to create the first one.",
    viewSwitcherLabel: "View",
    viewList: "List",
    viewBoard: "Board",
    boardColumnEmpty: "No tasks in this status.",
    taskMoveFailed: "Couldn't move the task. It was returned to its previous column.",
    taskName: "Task name",
    taskStatus: "Status",
    taskStartDate: "Start date",
    taskDueDate: "Due date",
    taskEstimate: "Estimate (days)",
    taskAssigneeRole: "Assignee role",
    taskDescription: "Description",
    taskActivity: "Activity",
    addTask: "Add task",
    deleteTask: "Delete task",
    confirmDelete: "Sure?",
    taskCreated: "Task created",
    taskDeleted: "Task deleted",
    taskUpdated: "Task updated",
    undo: "Undo",
    close: "Close",
    lastTaskInPackage: "This is the last task in its package and can't be deleted.",
  },
  ar: {
    brand: "إكس‌كولاب",
    tagline: "صِف المهمة، ويُبنى البرنامج تلقائيًا.",
    missionLabel: "موجز المهمة",
    missionPlaceholder: "مثال: إطلاق برنامج لوجستيات ميدانية سيادية عبر ثلاثة مراكز إقليمية",
    timelineStart: "البداية",
    timelineEnd: "النهاية المستهدفة",
    generate: "توليد البرنامج",
    generating: "جارٍ التوليد…",
    programsHeading: "البرامج",
    emptyState: "لا توجد برامج بعد. اكتب مهمة أعلاه لتوليد أول برنامج.",
    ledgerVerified: "تم التحقق من السجل",
    ledgerInvalid: "فشل التحقق من السجل",
    ledgerHeading: "سجل إجراءات الذكاء الاصطناعي",
    packagesHeading: "حِزم العمل",
    tasksLabel: "مهام",
    milestonesHeading: "المعالم",
    risksHeading: "المخاطر",
    teamsHeading: "الفرق",
    generatedBy: "تم التوليد بواسطة",
    errorGeneric: "فشل التوليد. تأكد من تشغيل الخادم ثم أعد المحاولة.",
    languageToggle: "English",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystem: "تلقائي",
    navOverview: "نظرة عامة",
    navPrograms: "البرامج",
    navLedger: "سجل الذكاء الاصطناعي",
    navTeams: "الفرق",
    navSoon: "قريبًا",
    workspace: "مساحة عمل المقر",
    statPrograms: "البرامج",
    statPackages: "حزم العمل",
    statTasks: "المهام",
    statChain: "سلامة السلسلة",
    statusTodo: "قيد الانتظار",
    statusInProgress: "قيد التنفيذ",
    statusBlocked: "معلّق",
    statusDone: "مكتمل",
    actorHuman: "إنسان",
    actorAi: "ذكاء اصطناعي",
    actorService: "خدمة",
    severityLow: "منخفضة",
    severityMedium: "متوسطة",
    severityHigh: "مرتفعة",
    severityCritical: "حرجة",
    colSeq: "التسلسل",
    colActor: "الفاعل",
    colAction: "الإجراء",
    colModel: "النموذج",
    colTime: "وقت الحدوث",
    colHash: "البصمة",
    colPrevHash: "البصمة السابقة",
    chainIntact: "كل إدخال يتحقق من بصمته ويرتبط بسابقه.",
    chainBrokenAt: "فشل التحقق من السلسلة",
    backToPrograms: "العودة إلى البرامج",
    notFound: "البرنامج غير موجود.",
    openProgram: "فتح",
    estimateDaysSuffix: "أيام",
    ledgerEmpty: "لا توجد إدخالات بعد. ولّد برنامجًا لإنشاء أول إدخال.",
    viewSwitcherLabel: "طريقة العرض",
    viewList: "قائمة",
    viewBoard: "لوحة",
    boardColumnEmpty: "لا توجد مهام في هذه الحالة.",
    taskMoveFailed: "تعذّر نقل المهمة، وأُعيدت إلى عمودها السابق.",
    taskName: "اسم المهمة",
    taskStatus: "الحالة",
    taskStartDate: "تاريخ البدء",
    taskDueDate: "تاريخ الاستحقاق",
    taskEstimate: "التقدير (أيام)",
    taskAssigneeRole: "دور المكلَّف",
    taskDescription: "الوصف",
    taskActivity: "النشاط",
    addTask: "إضافة مهمة",
    deleteTask: "حذف المهمة",
    confirmDelete: "متأكد؟",
    taskCreated: "تم إنشاء المهمة",
    taskDeleted: "تم حذف المهمة",
    taskUpdated: "تم تحديث المهمة",
    undo: "تراجع",
    close: "إغلاق",
    lastTaskInPackage: "هذه آخر مهمة في حزمتها ولا يمكن حذفها.",
  },
};
