export type UiLanguage = "en" | "ar";

interface Dictionary {
  brand: string;
  tagline: string;
  missionLabel: string;
  missionPlaceholder: string;
  timelineStart: string;
  timelineEnd: string;
  generate: string;
  generating: string;
  programsHeading: string;
  emptyState: string;
  ledgerVerified: string;
  ledgerInvalid: string;
  ledgerHeading: string;
  packagesHeading: string;
  tasksLabel: string;
  milestonesHeading: string;
  risksHeading: string;
  teamsHeading: string;
  generatedBy: string;
  errorGeneric: string;
  languageToggle: string;
  themeLight: string;
  themeDark: string;
  themeSystem: string;
}

export const STRINGS: Record<UiLanguage, Dictionary> = {
  en: {
    brand: "XCollab",
    tagline: "Describe the mission. The program builds itself.",
    missionLabel: "Mission brief",
    missionPlaceholder:
      "e.g. Stand up a sovereign field-logistics program across three regional hubs by Q4",
    timelineStart: "Start",
    timelineEnd: "Target end",
    generate: "Generate program",
    generating: "Generating…",
    programsHeading: "Programs",
    emptyState: "No programs yet. State a mission above to generate the first one.",
    ledgerVerified: "Ledger verified",
    ledgerInvalid: "Ledger verification failed",
    ledgerHeading: "AI action ledger",
    packagesHeading: "Work packages",
    tasksLabel: "tasks",
    milestonesHeading: "Milestones",
    risksHeading: "Risks",
    teamsHeading: "Teams",
    generatedBy: "Generated by",
    errorGeneric: "Generation failed. Check that the API is running and try again.",
    languageToggle: "العربية",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "Auto",
  },
  ar: {
    brand: "إكس‌كولاب",
    tagline: "صِف المهمة، ويُبنى البرنامج تلقائيًا.",
    missionLabel: "موجز المهمة",
    missionPlaceholder: "مثال: إطلاق برنامج لوجستيات ميدانية سيادية عبر ثلاثة مراكز إقليمية",
    timelineStart: "البداية",
    timelineEnd: "النهاية المستهدفة",
    generate: "توليد البرنامج",
    generating: "جارٍ التوليد…",
    programsHeading: "البرامج",
    emptyState: "لا توجد برامج بعد. اكتب مهمة أعلاه لتوليد أول برنامج.",
    ledgerVerified: "تم التحقق من السجل",
    ledgerInvalid: "فشل التحقق من السجل",
    ledgerHeading: "سجل إجراءات الذكاء الاصطناعي",
    packagesHeading: "حِزم العمل",
    tasksLabel: "مهام",
    milestonesHeading: "المعالم",
    risksHeading: "المخاطر",
    teamsHeading: "الفرق",
    generatedBy: "تم التوليد بواسطة",
    errorGeneric: "فشل التوليد. تأكد من تشغيل الخادم ثم أعد المحاولة.",
    languageToggle: "English",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystem: "تلقائي",
  },
};
