apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcollab.fullname" . }}-api
  labels:
    {{- include "xcollab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "xcollab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcollab.fullname" . }}-web
  labels:
    {{- include "xcollab.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "xcollab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
